title: Page Counter
description: Add-On that counts the number of pages in a selection or query of documents. 
instructions: ''
documents:
  - query
  - selected
properties: {}
categories: 
  - file
# Acceptable categories are premium, ai, export, bulk, file,  monitor, statistical, and extraction. 
# You can read more about DocumentCloud Add-On categories here: https://www.documentcloud.org/help/add-ons#types-of-add-ons
version: 2
